name: Notificación de Telegram

on:
  push:

jobs:
  enviar-mensaje:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar mensaje a Telegram
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="🚀 Se realizó un nuevo push en el repositorio ${{ github.repository }}. Autor: ${{ github.actor }}"